# Usamos una imagen base oficial de Node.js
FROM node

# Definimos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos necesarios para la aplicación
COPY package.json .
COPY index.js .

# Instalamos las dependencias
RUN npm install

# Exponemos el puerto en el que la aplicación estará escuchando
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "index.js"]