version: '3'
services:
  mqtts:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    # restart: always
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pocsystem
      - MYSQL_DATABASE=pocsystem
    networks:
      - backend
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - mqtts
    
networks:
  backend: